### ISSUE TITLE
Can i automatically sending a message without user command? 

### ISSUE THREAD

**Issue by hengvenchang** [DinoLeung/TeleDart#105]
I want to have a simple method like this 

teledart.sendMessage( 'Hello')

right now! we have to wait before we can reply  
teledart
        .onCommand('hello')
        .listen(((message) => teledart.replyMessage(message, 'world')));

**Comment by DinoLeung** [comment]
@hengvenchang see: https://github.com/DinoLeung/TeleDart/blob/6f8e7bb9f1fa0ff62455ac92e839ef10519cd038/lib/src/telegram/telegram.dart#L140
