### ISSUE TITLE
Fields in telegram objects

### ISSUE THREAD

**Issue by syfulin** [DinoLeung/TeleDart#116]
1. In class **InlineQueryResultGif** lacks field _thumb_mime_type_. 
2. In class **InlineQueryResultMpeg4Gif** lacks field _thumb_mime_type_. 
3. In class **PassportElementErrorUnspecified** instead of _file_hash_ there should be _element_hash_
4. In method **restrictChatMember(...)** incorrectly formed value of _requestUrl_ and unnecessary fields

**Comment by syfulin** [comment]
4. In method **restrictChatMember(...)** incorrectly formed value of _requestUrl_ and unnecessary fields

**Comment by DinoLeung** [comment]
fixed in https://github.com/DinoLeung/TeleDart/commit/5341f717fb0dfb89dc6cfcca2b454a3a3caa3d01
