### ISSUE TITLE
Handling updates independently

### ISSUE THREAD

**Issue by dmiedev** [DinoLeung/TeleDart#122]
## Is your feature request related to a problem?
Yes. I want to have a Telegram bot written in Dart and deployed with Firebase Cloud Functions and webhooks so my cloud function gets called by Telegram app when users send messages to the bot. That's why I have to handle updates independently (I don't need to listen, i.e. to call `start()`). But the problem is that `_updatesHandler()` method is private.

So what I'm trying to achieve is this:
Set webhook manually with help of Telegram's `setWebhook()` method via http request to my cloud function, then
> Telegram bot message -> Cloud function -> handle update

For example, in Node.JS framework called Telegraf, they have [`handleUpdate()`](https://telegraf.js.org/#/?id=handleupdate) method, and if I was using it, I would have to do [something like this](https://github.com/telegraf/telegraf/issues/98#issuecomment-321740763) (to call `handleUpdate()` when my cloud function is called).

## Describe the solution you'd like
I'd like to have the `_updatesHandler()` method public:

```dart
  /// Private method to add updates into events queue
  void updatesHandler(Update update) => _event.emitUpdate(update);
```

Or something similar:

```dart
  /// Handle raw Telegram update. In case you use centralized webhook server, queue, etc.
  void handleUpdate(Update update) => _updatesHandler(update);
```

Or any other solution...

Thanks!

**Comment by DinoLeung** [comment]
@dmiedev very interesting idea, I will need to do some research myself before comming up with a solution.

**Comment by simolus3** [comment]
@DinoLeung Did you come up with anything yet? I also need this feature, and I'm happy to open a PR if you're not working on this at the moment.

My approach would be to factor out the `setWebHook()`, `startWebhook()`, `stopWebhook()` and most importantly `onUpdate()`  methods into an abstract `BaseWebhook` class that users could implement themselves. We could then have a `setupCustomWebhook(BaseWebhook webhook)` method in `TeleDart` which would use a custom webhook. An advantage is that this would work together with the `start()` and `removeWebhook()` methods of `TeleDart`.

**Comment by DinoLeung** [comment]
@dmiedev check out the recent pull request 👆

**Comment by dmiedev** [comment]
Thanks @simolus3
