### ISSUE TITLE
Keyword detection in message with hashtag

### ISSUE THREAD

**Issue by syfulin** [DinoLeung/TeleDart#124]
Is it possible to use teledart to process a message with a keyword if the message contains a hashtag?

     teledart
      ..start(webhook: false).then((User user) => me = user)

      // Will not work if the message has a hashtag:
      ..onMessage(keyword: 'Hi').listen((message) {teledart.replyMessage(message, 'Hello');})
      
      ..onHashtag().listen((message) {teledart.replyMessage(message, 'I\'ts hashtag');});

Example: https://ibb.co/JC7HTrs,

**Comment by DinoLeung** [comment]
see https://github.com/DinoLeung/TeleDart/blob/7f7dfb7d7315c02d8904ad7d97087e9f886f983d/example/main.dart#L42
you can take advantage of [stream processing methods](https://www.dartlang.org/tutorials/language/streams#methods-that-modify-a-stream)

**Comment by syfulin** [comment]
As a supplement, I will give an example of code that solves my problem.

Objective: Process absolutely all messages that contain the word 'Hi' in the text.

Code:
```
teledart
.onMessage(entityType: '*')
..where((message) => ((message.text?.contains('Hi')) ?? false))
.listen((message) => teledart.replyMessage(message, 'Hello'));
```

**Comment by DinoLeung** [comment]
@syfulin glad you found your solution.
Just to make things clear for you, by omitting `entityType`, it will give you a stream messages which contains no [messageentity](https://core.telegram.org/bots/api#messageentity). See #40 for more information.
