### ISSUE TITLE
restrictChatMember cant convert chat permissions object to an encodable object

### ISSUE THREAD

**Issue by Bergiu** [DinoLeung/TeleDart#126]
## Describe the bug
I am trying to mute users, but instead i get this error:
`Converting object to an encodable object failed: Instance of 'ChatPermissions'`

## To Reproduce
Snippet to reproduce the behavior:
```dart
var chat_id = message.chat.id;
var user_id = message.user.id;
var permissions = new ChatPermissions(can_send_messages: false);
var until_date = DateTime.now().millisecondsSinceEpoch + (7 * 24 * 60 * 60);
telegram.restrictChatMember(chat_id, user_id,
               permissions: permissions, until_date: until_date);
```

## Expected behavior
I expected that the user is muted, but it was not muted.

## Additional context
The user has no admin rights, it's a supergroup and i'm a dart newbie.

**Comment by Bergiu** [comment]
I fixed it with some changes:
1. Replacing line 44 and 45 of https://github.com/DinoLeung/TeleDart/blob/master/lib/src/telegram/models/chat_permissions.dart#44 with this: `Map<String, dynamic> toJson() => _$ChatPermissionsToJson(this);`
2. Replace line 885 of https://github.com/DinoLeung/TeleDart/blob/master/lib/src/telegram/telegram.dart#L885 (`var requestUrl = '${_baseUrl}${_token}/unbanChatMember';`) with this: `var requestUrl = '${_baseUrl}${_token}/restrictChatMember';`

**Comment by Bergiu** [comment]
Nice. When will it be released?

**Comment by DinoLeung** [comment]
Will do a release as soon as #125 is merged in, I'm hoping this weekend
