### ISSUE TITLE
Exceptions for actual errors (no json response)

### ISSUE THREAD

**Issue by castaway** [DinoLeung/TeleDart#137]
## Describe the bug
I managed to generate a "Bad Request" error (by sending parse_mode: 'MarkdownV2' on sendMessage), which just gives me an exception as "HttpClientException: null null" - I ended up having to put a breakpoint in your http client code to figure out what it was trying to tell me.

## To Reproduce
Snippet to reproduce the behavior:
```dart
teledart.telegram.sendMessage($someuserid, 'Some long text', parse_mode: 'MarkdownV2');
```

## Expected behavior
The client should output HttpClientException: (400) (Bad Request)

## Additional context
As to why I'm getting a Bad Request, I'm not sure - I've messaged telegram support to ask why (as teledart is just passing through my parse_mode string)

**Comment by DinoLeung** [comment]
sorry for the delay @castaway will get to this the weekend

**Comment by DinoLeung** [comment]
@castaway please check out the [Telegram markdown v2 documentation](https://core.telegram.org/bots/api#markdownv2-style), I assumed you are trying to send some special characters with markdown v2. E.g. If I'm sending the sentence `Hello Teledart!`, the reply code should read `teledart.telegram.sendMessage(message.chat.id, 'Hello TeleDart!', parse_mode: 'MarkdownV2')`

**Comment by castaway** [comment]
I think I was just trying to send "*some text* something else" or similar.. cant remember any more! Thanks for the update!
