### ISSUE TITLE
"null" messages are not handled

### ISSUE THREAD

**Issue by dmbaranov** [DinoLeung/TeleDart#156]
## Describe the bug
I created a simple echo bot and if I send it a message "null", it fails with 
```
Unhandled exception:
HttpClientException: 400 Bad Request: message text is empty
```

I checked the code and apparently, the issue is hidden in [this line](https://github.com/DinoLeung/TeleDart/blob/master/lib/src/util/http_client.dart#L24). I decided to open an issue, not a PR, because I'm not sure if the 2nd part of that condition can be simply removed or it should be handled differently.

## To Reproduce
Snippet to reproduce the behavior:
```dart
void main(String token) async {
  var telegram = Telegram(token);
  var bot = TeleDart(telegram, Event());

  await bot.start();

  bot.onMessage(entityType: '*').listen((TeleDartMessage message) {
    message.reply(message.text);
  });
}

// write null to the bot
```

## Expected behavior
I can send a message with content "null"

**Comment by gituwalie** [comment]
Same appears when user suspends the bot
is there any WA for this?
