### ISSUE TITLE
RegExp message matching doesn't work at all.

### ISSUE THREAD

**Issue by TrishaDes** [DinoLeung/TeleDart#157]
Simply, any regex that i use isn't valid, or, at least, it isn't going throught the listener, even if in a simple print(RegExp("expr").hasMatch()) works

## To Reproduce
Snippet to reproduce the behavior:
```dart
// Place snippet here
import 'package:teledart/teledart.dart';
import 'package:teledart/telegram.dart';

const String token = "TOKEN";
Telegram bot = Telegram(token);
TeleDart client = TeleDart(bot, Event());
void main() async {
  await client.start().then(
        (me) => print('Il bot @${me.username} è stato inizializzato.'),
      );

  await client
      .onCommand(RegExp(r'send [\d]+ .+', dotAll: true, caseSensitive: false))
    ..listen((event) {
      print("Listened.");
    });
}
```

at this point, if you write /send ANY_NUMBER everything you want
it wont work, for example:
/send 123456789 hello world!

**Comment by DinoLeung** [comment]
Thanks for reaching @TrishaDes 

This is not a bug, rather it's an expected behavour. According to [Telegram bots API documentation](https://core.telegram.org/bots/api#botcommand) command string cannot contain spaces. If you need to get the message after the command, you can consider using the function below. 


```
String getCommandQuery(Message message) {
  var entity = message.entityOf('bot_command');
  return message.text.substring(entity.offset + entity.length).trim();
}
```

**Comment by TrishaDes** [comment]
Oh i see, thanks, i thought it was a bug, sorry for bothering you :)
