### ISSUE TITLE
sound null safety

### ISSUE THREAD

**Issue by DinoLeung** [DinoLeung/TeleDart#164]
## Describe the solution you'd like
`json_annotation` is deprecating `nullable` option and will determine by the new sound null safety introduced in Dart 2.12.0

Some code snippet would help? 
```dart
String? foo; // This requires the 'non-nullable' language feature to be enabled.
```

## Additional context
https://pub.dev/packages/json_annotation/changelog#400
https://pub.dev/packages/http/changelog#0130-nullsafety0
https://dart.dev/null-safety/migration-guide

**Comment by Azzeccagarbugli** [comment]
This is becoming a must have, should be a priority right now I guess. Unfortunately I don't have enough time to do a PR but with the Dart tools could be really easy to migrate!
