### ISSUE TITLE
HttpClientException: 409 Conflict

### ISSUE THREAD

**Issue by Azzeccagarbugli** [DinoLeung/TeleDart#174]
## Describe the bug
I'm running the bot in a **Flutter web application** and after some time I get an error about the fact that there are more than one `bot instance` running.

<details>
<summary>Console log</summary>
<br>

```
Error: LongPollingException: HttpClientException: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at Object.throw_ [as throw] (http://localhost:64465/dart_sdk.js:5037:11)
    at long_polling.LongPolling.new.[_onRecursivePollingHttpError] (http://localhost:64465/packages/teledart/src/teledart/fetch/long_polling.dart.lib.js:117:19)
    at http://localhost:64465/packages/teledart/src/teledart/fetch/long_polling.dart.lib.js:109:89
    at _RootZone.runUnary (http://localhost:64465/dart_sdk.js:37245:59)
    at _FutureListener.catchError.handleError (http://localhost:64465/dart_sdk.js:32513:48)
    at handleError (http://localhost:64465/dart_sdk.js:33044:51)
    at Function._propagateToListeners (http://localhost:64465/dart_sdk.js:33070:17)
    at _Future.new.[_completeError] (http://localhost:64465/dart_sdk.js:32920:23)
    at http://localhost:64465/dart_sdk.js:33137:38
```

</details>

## To Reproduce
Snippet to reproduce the behavior:
```dart
class Bot {
  factory Bot() {
    return _instance;
  }

  Bot._internal();

  final teledart = TeleDart(
    Telegram(env['TELEGRAM_BOT_TOKEN']!),
    Event(),
  );

  Future<User?> start() async {
    try {
      await teledart.start();
    } catch (e) {
      debugPrint(e as String);
    }
  }

  static final Bot _instance = Bot._internal();
}

```

## Expected behavior
Since I'm using a [singleton](https://en.wikipedia.org/wiki/Singleton_pattern) I would already expect that the `bot instance` is the only one generated.

## Additional context
Maybe is just Flutter messing up with that, I'm not able to understand it. Could be also the fact that I'm already hosting it in a web server so each user that connects to it is creating another instance, with the same bot token obviously. In this case I really don't know how to fix this rather than have a backend but I'm open to suggestions!

**Comment by YTawfik** [comment]
same here

**Comment by DinoLeung** [comment]
@Azzeccagarbugli @YTawfik 409 errors are definitely related to multiple instances trying to make `getUpdate` requests at the same time. If you are running the bot in a Flutter web app, which obviously is a front-end framework, then it's very likely that each browser client will have their own singleton instance. Although I'm not an expert on Flutter and singleton pattern in Dart. I believe the Bot instance should run on the server side not client side, and if you need redundancy consider using webhook.
