### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by leonidussaks** [DinoLeung/TeleDart#179]
## Describe the bug
Hello, i'am new to Dart. Here is my code taken from example

```
import 'dart:io' show Platform;
import 'package:teledart/teledart.dart';
import 'package:teledart/telegram.dart';

Future<void> main() async {
  final envVars = Platform.environment;

  var telegram =
      Telegram(envVars['token']!);
  var event = Event((await telegram.getMe()).username!);
  var teledart = TeleDart(telegram, event);

  teledart.start();

  teledart.onMessage(entityType: 'bot_command', keyword: 'start').listen(
      (message) =>
          teledart.telegram.sendMessage(message.chat.id, 'Hello TeleDart!'));
}

```

after running I get the error:
```

Unhandled exception:
Null check operator used on a null value
#0      main (file:///home/leonidussaks/development/telegram_bot_dart/bin/telegram_bot_dart.dart:10:73)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by DinoLeung** [comment]
@leonidussaks have you declare the environment variable `token` in your terminal session? You should be able to create your token from bot father

**Comment by paulobreim** [comment]
See this video:
https://www.youtube.com/watch?v=z70ov74yOWs&t=3s&ab_channel=paulobreim

**Comment by sinaf2000** [comment]
> @leonidussaks have you declare the environment variable `token` in your terminal session? You should be able to create your token from bot father

i have problem

my code:
```
import 'dart:io' show Platform;

import 'package:teledart/teledart.dart';
import 'package:teledart/telegram.dart';
import 'package:teledart/model.dart';

Future<void> main() async {
  final envVars = Platform.environment;
  var telegram = Telegram(envVars['1921256102:AAGgYGWg3vn__sR9viT7DM8SQjVS0UIAiik']!);
  var event = Event((await telegram.getMe()).username!);

  TeleDart(telegram, event)
  ..start()
  ..onMessage(keyword: 'Fight for freedom')
      .listen((message) => message.reply('Stand with Hong Kong'));
}
```

and error :
**Unhandled exception:
Null check operator used on a null value
#0      main (file:///C:/Users/asus/Desktop/telegrambot/bin/telegrambot.dart:9:84)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)**
please help me

**Comment by DinoLeung** [comment]
@sinaf2000 The following line initialise a `Telegram` object with the environment variable `token`  
```
var telegram = Telegram(envVars['token']!);
```
So you will need to declare `token` in your terminal session, I'm not sure how to do that in Windows, but on Linux/MacOS you declare it by executing `export token="123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"`

**Comment by leonidussaks** [comment]
> @sinaf2000 The following line initialise a `Telegram` object with the environment variable `token`
> 
> ```
> var telegram = Telegram(envVars['token']!);
> ```
> 
> So you will need to declare `token` in your terminal session, I'm not sure how to do that in Windows, but on Linux/MacOS you declare it by executing `export token="123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"`

Sorry,i was grossly mistaken as the person above. Thanks for help!

**Comment by ashdelta1023** [comment]
> in windows is you can set via command
> setx token "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"

Set Token in Terminal But Still getting Below Error in example App.

```
E/flutter ( 3777): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 3777): #0      main
package:teledart_test/main.dart:11
E/flutter ( 3777): #1      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter ( 3777): #2      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 3777): #3      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 3777): #4      _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 3777): #5      runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 3777): #6      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
```

**Comment by DinoLeung** [comment]
@ashdelta1023 Would you be able to post the code snippet to reproduce the error?

**Comment by sikandernoori** [comment]
> var telegram =
>       Telegram(envVars['token']!);

I think envVars is confusing many developers.

For anyone not sure about envVars they don't need to setup environment variable instead they can directly use token like below.

`  var telegram = Telegram('tokenstring');`
