### ISSUE TITLE
`photo` property of `TeleDartMessage` have length 4

### ISSUE THREAD

**Issue by kharitonovAL** [DinoLeung/TeleDart#184]
## The bug
Hi there!

I'm trying to get images that was passed to my telegram bot  by user and store them on remote server. To do this I want to get images from `photo` property of `TeleDartMessage` that have return type `List<PhotoSize>?`.
But for some reason the `photo.length` is always equals 4, no mater if user send 1 or 5 photos.

## To Reproduce
Snippet to reproduce the behavior:
```dart
teledart.telegram.sendMessage(
      message.chat.id,
      'add photos',
    );
final messageSubscription = teledart.onMessage().listen((_) {});
messageSubscription.onData((data) async {
   print(data.photo!.length);
}
```

## Expected behavior
For my opinion, the `photos` property has to return the amount of objects (photos) that was sent by user.

Thank you!

**Comment by kharitonovAL** [comment]
So the right answer is that `photo` property of `TeleDartMessage` contains four different photo's dimension (first is the smallest and most worse quality, and the last is the biggest and best image quality).

And the code snippet from above:
```dart
// ...
messageSubscription.onData((data) async {
   print(data.photo!.length);
}
```

will be triggered every time when you send photo to bot, until the subscription will be canceled.

But may be it has to be described in the documentation?
Thanks!

**Comment by DinoLeung** [comment]
Hi @kharitonovAL , glad you have found it out. It's actually says in [official doc](https://core.telegram.org/bots/api#message) `Message is a photo, available sizes of the photo`, although it does not mention how many different sizes will be included and it could change over time. If the message contains multiple images, it will be encapsulated in a [media group](https://core.telegram.org/bots/api#sendmediagroup)

**Comment by kharitonovAL** [comment]
> Hi @kharitonovAL , glad you have found it out. It's actually says in [official doc](https://core.telegram.org/bots/api#message) `Message is a photo, available sizes of the photo`, although it does not mention how many different sizes will be included and it could change over time. If the message contains multiple images, it will be encapsulated in a [media group](https://core.telegram.org/bots/api#sendmediagroup)

Hi @DinoLeung ,
Thanks for the info! I think I just have to read better the documentation.
