### ISSUE TITLE
There is no Api Hash and Api code Implementation Just Mention that 

### ISSUE THREAD

**Issue by RakulAgn** [DinoLeung/TeleDart#185]
![Screenshot (60)](https://user-images.githubusercontent.com/70213104/140685743-ee8ebeb0-b073-459b-8f08-a47f138d1bd6.png)

**Comment by DinoLeung** [comment]
@RakulAgn would you be able to post your code snippet here? I suspect your not token is invalid or absence, therefore telegram returns a 404 error.

**Comment by RakulAgn** [comment]
Bot Token is Valid
