### ISSUE TITLE
Get Group ID

### ISSUE THREAD

**Issue by kholyphoenix0** [DinoLeung/TeleDart#199]
Hello, 
I don't know how I can get the Group ID so that the Bot responds only in the Group (Private).

can anybody help me?
Thanks!

**Comment by HeySreelal** [comment]
If your bot is on the private group and can read the messages, `message.chat.id` will give you the group id.
And you can respond like:
`teledart.sendMessage(message.chat.id, 'Hey!');`

**Comment by DinoLeung** [comment]
@HeySreelal thanks for answering this issue.
