### ISSUE TITLE
Unhandled ClientException flutter

### ISSUE THREAD

**Issue by carveza23** [DinoLeung/TeleDart#205]
## Describe the bug
If I use the example code in a simple flutter application with internet connection on, everything works fine, but if I turn off the internet connection an exception of type ClientException is thrown.
The app becomes unusable at this moment with a black screen.
It is possible to handle these errors in some way?
The problem I think is with the updates of the long polling.

## To Reproduce
The example code in a flutter application.

## Expected behavior
No error should be thrown or a method to handle the error

**Comment by DinoLeung** [comment]
throwing exception when there's no internet connection is an expected behavior, you should catch the exception in your Flutter application to prevent the application from crashing
