### ISSUE TITLE
getUpdates

### ISSUE THREAD

**Issue by FiKa404** [DinoLeung/TeleDart#208]
```
import 'package:teledart/model.dart';
import 'package:teledart/teledart.dart';
import 'package:teledart/telegram.dart';

void main() async {
  var BOT_TOKEN = 'BOT_TOKEN';
  final username = (await Telegram(BOT_TOKEN).getMe()).username;
  var teledart = TeleDart(BOT_TOKEN, Event(username!));

  var x = teledart.getUpdates(timeout: 60);
  teledart.start();
  Stream.fromFuture(x).listen((event) {
    for(var i in event){
      print(i.message?.text);
    }
  });
  
}
```
I'm trying to make stream of updates but i can't 
could u make a little example for that in docs

**Comment by DinoLeung** [comment]
See [event.dart](https://github.com/DinoLeung/TeleDart/blob/master/lib/src/teledart/event/event.dart) for example of creating event streams. In fact, for normal use cases, following the [example](https://github.com/DinoLeung/TeleDart/blob/master/example/main.dart) would probably be sufficient
