### ISSUE TITLE
delete messsage dont work 

### ISSUE THREAD

**Issue by mohammadprgrm20123** [DinoLeung/TeleDart#209]

**Comment by mohammadprgrm20123** [comment]
can't remove message for everyone

**Comment by HeySreelal** [comment]
@mohammadprgrm20123, can you provide a little more details about the issue? 

You can use the ```TeleDart.deleteMessage``` passing the `chat_id` and `message_id` to delete a message. And it's working fine.

Example:
```dart
await teleDart.deleteMessage(chat_id, message_id);
print("Message deleted");
```

If an error happened the method will throw an error. If that's the case, please share the error details for a better solution.

**Comment by DinoLeung** [comment]
Thanks @HeySreelal 🥂 . Closing this for now, @mohammadprgrm20123 you are welcome to re-open this issue will further information so the community has a better insight to help you over come the issue you are experiencing.
