### ISSUE TITLE
Send message to a telegram user

### ISSUE THREAD

**Issue by PavieOlivier** [DinoLeung/TeleDart#210]
## Is your feature request related to a problem?
Would like to send a notification text to a particular user 

## Describe the solution you'd like
Would like the possibility to send a message to a user subscriber to a bot . or directly to a user

Some code snippet would help? 
```dart
/NA
```

## Additional context
Everything something happens on the server, I would like to send a message to a user

**Comment by HeySreelal** [comment]
You can already use the `TeleDart.sendMessage` method to send messages to a particular user. The only condition is the user has to be subscribed earlier (Telegram Bots can't initiate a conversation with a user). 

For example, let's say you're building a weather reporting bot, and when new weather data is available you can send a message to subscribers with the `sendMessage` method.

```dart
void sendWeatherUpdate() async {
  // You'll have to store the subscriber's chat_id on a dedicated database.
  var userId = "<USER'S TELEGRAM ID>";

  // Get the weather update from your weather API or the content you want to send to the user.
  var content =
      "In the north of the country, it's very windy and cold. There is a chance of some rain too, so don't leave home without your umbrella!";

  // Send the message to the user
  await teleDart.sendMessage(userId, content);

  print("Weather update is sent");
}

```

<hr> 

Hope this helps :)
If you got any further doubts or questions don't be hesitated to ask away.

**Comment by DinoLeung** [comment]
Thanks @HeySreelal for providing a working solution for this request. It's good to see the community has started to grow and people are helping each other within the user group. But keep in mind that GitHub issue is meant for submitting bug reports/feature requests, for general help or other discussions [GitHub discussions](https://github.com/DinoLeung/TeleDart/discussions) is a more suitable place.

**Comment by PavieOlivier** [comment]
Thanks a lot :) 
This will be very useful
