### ISSUE TITLE
Loop for cath exception

### ISSUE THREAD

**Issue by Lysmi** [DinoLeung/TeleDart#227]
Whats about auto-restart teledart the program catches the exception? For create own exceptions handlers.
I tried use while and async function, but it doesn`t work.

**Comment by DinoLeung** [comment]
I'm not sure about auto-restarting the server, it should be the platform's responsibility rather. For example I deploy my bot as a container using docker, i should setup docker to restart the bot container when it's crashed.

You can handle errors like below, see [documentation](https://api.dart.dev/stable/2.19.1/dart-async/Stream/listen.html) of stream.
```
teledart.onCommand(RegExp('hello', caseSensitive: false)).listen(
      (message) => message.reply('hi!'),
      onError: (e) => print('Error catched: $e'));
```

**Comment by DinoLeung** [comment]
closing as inactive
