### ISSUE TITLE
Export HttpClientException

### ISSUE THREAD

**Issue by busslina** [DinoLeung/TeleDart#234]
For example, when I'm updating a message inline keyboard, using `editMessageReplyMarkup`, I need to catch HttpClientException (when HTTP 400 status code) that is triggered beacuse of inline keyboard data is the same.

Now I am importing this class like this:
![imagen](https://user-images.githubusercontent.com/73592852/216562850-e58f8d0f-a9aa-4470-a469-db769443e6f2.png)

It works but it should be exported correctly in order that warning disappears.

![imagen](https://user-images.githubusercontent.com/73592852/216561803-2beff1a3-4fa9-43a3-af89-bf4bd0ecdcd7.png)

**Comment by HeySreelal** [comment]
Hey, as far as I know, the `HttpClientException` class is not exported by the TeleDart package. It's only used by the package itself internally.

Hence this happens :)

**Comment by busslina** [comment]
> Hey, as far as I know, the `HttpClientException` class is not exported by the TeleDart package. It's only used by the package itself internally.
> 
> Hence this happens :)

Exactly, this is why I added this feature request. When this exception is thrown and not catched internally (you can catch it externally) I think it should be exported (so warning message dissapears).

Have a good day
