### ISSUE TITLE
Bad ErrorResponse object build when 'parameters' is null

### ISSUE THREAD

**Issue by busslina** [DinoLeung/TeleDart#236]
While removing message (Telegram.deleteMessage), at reading HttpClient response data (in http_client.dart, line 43). Response data is: {ok: false, error_code: 400, description: Bad Request: message can't be deleted}.

In teledart\lib\src\telegram\model.g.dart, line 3578, the read of 'parameters' field is failling when it is null, because you are reading it as Map<String, dynamic>.

One possible workaround is to declare ResponseParameters parameters as nullable (response.dart file, line 68).

I will try to fix it (looking for edit the minimun amount of code) and if I succed I will create a PR.

> Unhandled exception:
> type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
> #0      _$ErrorResponseFromJson (package:teledart/src/telegram/model.g.dart:3578:30)
> #1      new ErrorResponse.fromJson (package:teledart/src/telegram/models/response.dart:78:7)
> #2      HttpClient._parseResponse (package:teledart/src/util/http_client.dart:43:51)
> #3      _rootRunUnary (dart:async/zone.dart:1399:47)
> #4      _CustomZone.runUnary (dart:async/zone.dart:1300:19)
> <asynchronous suspension>
> #5      Telegram.deleteMessage (package:teledart/src/telegram/telegram.dart:2346:12)
> <asynchronous suspension>
> #6      TelegramMessageRegister.removeMessages.<anonymous closure> (package:busslina_dart_rest_lib/core/modules/telegram/telegram_message_register.dart:47:14)
> <asynchronous suspension>
> #7      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
> <asynchronous suspension>
> #8      _TelegramHandler._getMenuCommandHandler (package:busslina_dart_rest_lib/core/modules/system.module.dart:175:5)
> <asynchronous suspension>
> #9      TelegramBot.onCommand.<anonymous closure> (package:busslina_dart_telegram_lib/src/core/app/telegram_bot.dart:137:11)
> <asynchronous suspension>
> #10     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)

**Comment by busslina** [comment]
Resolved easy. I added the changes to my previous PR (https://github.com/DinoLeung/TeleDart/pull/235)

**Comment by busslina** [comment]
``

**Comment by guid-empty** [comment]
hi!
what's about this fix? is it possible to merge it to master in the nearest time?

**Comment by busslina** [comment]
> hi! what's about this fix? is it possible to merge it to master in the nearest time? the problem is actual, for example in the case when we use not allowed domain - error from server will be without parameters collection
> 
> <img alt="Pasted Graphic 22" width="1226" src="https://user-images.githubusercontent.com/17752828/225390622-50c2ad63-4e29-45b7-a0f0-098f0993f2bb.png">

You will have to wait maybe one month or the the time that the lib maintainer take to realise that. With this lib I decided to use my own fork in order to have all this issue fixed in a "short" time. I have done some fixes and minimal features like extending from Comparable class in Message and other classes. You are free to use it: https://github.com/busslina/TeleDart

**Comment by DinoLeung** [comment]
Sorry guys, life is a bit busy on my end. I'll try to squeeze some time to have a look at this and the pull request something this week.

Thanks for supporting the community
