### ISSUE TITLE
Photo message not getting 'text' value if provided?

### ISSUE THREAD

**Issue by busslina** [DinoLeung/TeleDart#239]
Text message value is always null, even if text comment is provided together with the photo, like in the image below:

![imagen](https://user-images.githubusercontent.com/73592852/226126147-1f34f698-328f-4a59-adaa-528e2593d250.png)

**Comment by HeySreelal** [comment]
Hey, it's not a bug. You're looking for the `caption` property. 

If the message is a text message, the `text` property will be filled, but if it's a photo message, the accompanying text will be considered a `caption`.

Regards :)

**Comment by busslina** [comment]
Thank you again @HeySreelal ;)
