### ISSUE TITLE
support for web app bot

### ISSUE THREAD

**Issue by rashedswen** [DinoLeung/TeleDart#245]
## Is your feature request related to a problem?
now telegram add web app inside telegrams bots who can do it or what steps I need to take in incorporate with js provided

**Comment by HeySreelal** [comment]
Web Apps are not bound by the Telegram Bot API library. You can read more here about how to create your Web App according to the Telegram Bot API guidelines here: https://core.telegram.org/bots/webapps#initializing-web-apps

By said that, you can already launch web apps using your Telegram bot by the following snippet:

```dart

TeleDart bot = TeleDart(
  Platform.environment["BOT_TOKEN"]!,
  Event("xclairebot"),
);

void main(List<String> args) {
  bot.sendMessage(
    Platform.environment["CHAT_ID"],
    "Choose option: ",
    replyMarkup: ReplyKeyboardMarkup(
      keyboard: [
        [
          KeyboardButton(
            text: "Open Web App",
            webApp: WebAppInfo(url: "https://google.com"),
          ),
        ]
      ],
    ),
  );

  bot.start();
}
```

There are recent changes in the Bot API 6.7, that allow you to launch web apps from the inline query results. [Check it out here](https://core.telegram.org/bots/api#april-21-2023).

**Comment by DinoLeung** [comment]
closing this since there's a solution to it

**Comment by rashedswen** [comment]
> Web Apps are not bound by the Telegram Bot API library. You can read more here about how to create your Web App according to the Telegram Bot API guidelines here: https://core.telegram.org/bots/webapps#initializing-web-apps
> 
> By said that, you can already launch web apps using your Telegram bot by the following snippet:
> 
> ```dart
> TeleDart bot = TeleDart(
>   Platform.environment["BOT_TOKEN"]!,
>   Event("<YOUR BOT USERNAME>"),
> );
> 
> void main(List<String> args) {
>   bot.sendMessage(
>     Platform.environment["CHAT_ID"],
>     "Choose option: ",
>     replyMarkup: ReplyKeyboardMarkup(
>       keyboard: [
>         [
>           KeyboardButton(
>             text: "Open Web App",
>             webApp: WebAppInfo(url: "https://google.com"),
>           ),
>         ]
>       ],
>     ),
>   );
> 
>   bot.start();
> }
> ```
> 
> There are recent changes in the Bot API 6.7, that allow you to launch web apps from the inline query results. [Check it out here](https://core.telegram.org/bots/api#april-21-2023).

thanks very much
