### ISSUE TITLE
Phone messages are not streamed to onMessage stream

### ISSUE THREAD

**Issue by busslina** [DinoLeung/TeleDart#247]
Every message, regardless its type, should be streamed to `onMessage `stream.

**Comment by Evgentret** [comment]
Using teledart.onPhoneNumber().listen is not forbidden. 
Messages from telegram had different entities, as for me - different listeners is better than parsing text. All works fine, it's not a bug but feature

**Comment by busslina** [comment]
> Also you can try to use teledart.onMessage(entityType: '*').listen((message)
Thank you for that, I didn't know I could listen for all kind of messages in this lib.

The thing here is that Telegram interpret 9 length numbered string as a phone number, event if it is not. I numbered string length is 8 or 10, it is not inerpreted as phone number. So if I am requesting a user to enter any input string, I wasn't able to retrieve his response via one handler:

```
bot.onMessage().forEach(_onMessage).catchError(_onReceivingError);
bot.onPhoneNumber().forEach(_onMessage).catchError(_onReceivingError);
bot.onEmail().forEach(_onMessage).catchError(_onReceivingError);
bot.onUrl().forEach(_onMessage).catchError(_onReceivingError);

```

It was my mistake to think there was no way to read all type of message, regardless its kind.

**Comment by DinoLeung** [comment]
As @Evgentret has mentioned, use `onMessage(entityType: '*')` to catch any type of messages
`onMessage()` is to catch messages with no `entityType`
