### ISSUE TITLE
is it still working ?

### ISSUE THREAD

**Issue by edoofx** [DinoLeung/TeleDart#253]
## Describe the bug
im using m1 , dart 3, test run on mac apps and got '[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Connection failed'

## To Reproduce
Snippet to reproduce the behavior:
```dart
  var BOT_TOKEN = mytoken;
  final username = (await Telegram(BOT_TOKEN).getMe()).username;
  var teledart = TeleDart(BOT_TOKEN, Event(username!));

  teledart.start()
```

**Comment by HeySreelal** [comment]
Hey, I tried to replicate this issue with Dart 3, on my M1. It was working fine. Can you please elaborate on the issue a little more? Or share the full stack trace of the error?

**Comment by HeySreelal** [comment]
Okay, okay now I get it. 

Can you check if you have registered the INTERNET permission for your app on `AndroidManifest.xml`? Here's the snippet:

```xml
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>
```

Let me know if this works, regards :)

**Comment by DinoLeung** [comment]
@edoofx Dart 3 support will be addressed in #256

**Comment by Kolovrat19** [comment]
final username = (await Telegram(BOT_TOKEN).getMe()).username;
    var teledart = TeleDart(BOT_TOKEN, Event(username!));
    teledart.deleteWebhook();
    teledart.start();

**Comment by DinoLeung** [comment]
Closing this as it's inactive. This library has no intention to support flutter, however it should work in flutter with the correct permission setup on the targeted platforms as @HeySreelal has pointed out.
