### ISSUE TITLE
HttpClientException should be exported.

### ISSUE THREAD

**Issue by abal1000x** [DinoLeung/TeleDart#260]
## Is your feature request related to a problem?
Yes. When i got `HttpClientException` from teledart, i couldn't catch it, because the exception class are not exported.

## Describe the solution you'd like
Refactor the `HttpClientException` out from `src/util/http_client.dart` and export it to the `teledart.dart`

Some code snippet would help? 
```dart
  Teledart teledart = Teledart(...);

  // This will throws HttpClientException with code 429, because its <10 minutes opened.
  teledart.close();
```

## Additional context
None.

**Comment by The0xArchitect** [comment]
Since #262 is merged, this issue also can be closed now. `HttpClientException` is also being exported now.

cc: @DinoLeung
