### ISSUE TITLE
Forcing optional param to exist

### ISSUE THREAD

**Issue by riccardocescon** [DinoLeung/TeleDart#265]
## Describe the bug
The stopPoll function reuires chatId, messageId and replyMarkup:
```dart
  Future<Poll> stopPoll(
      dynamic chatId, int messageId, InlineKeyboardMarkup replyMarkup) async {
    if (chatId is! String && chatId is! int) {
      return Future.error(TelegramException(
          'Attribute \'chatId\' can only be either type of String or int'));
    }
    var requestUrl = _apiUri('stopPoll');
    var body = <String, dynamic>{
      'chat_id': chatId,
      'message_id': messageId,
      'reply_markup': replyMarkup,
    };
    return Poll.fromJson(await HttpClient.httpPost(requestUrl, body: body));
  }
```
But the telegram api does not require replyMarkup, it's an optional parameter: https://core.telegram.org/bots/api#stoppoll

## Expected behavior
The replyMarkup should be nullable

**Comment by HeySreelal** [comment]
I've added the fix for this in #262, hoping this would get merged soon. In the meantime, if you're looking for a local fix, feel free to check this commit: 00341c96341b62d24b6f2fb85e7165cf73cc50e0

Regards!
