### ISSUE TITLE
LongPollingException: HttpClientException: 409 Conflict

### ISSUE THREAD

**Issue by MagicalWater** [DinoLeung/TeleDart#268]
## Describe the bug
If multiple bot instances are used or getUpdates is called manually, the following error will occur
```dart
LongPollingException: HttpClientException: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
#0      LongPolling._onRecursivePollingHttpError (package:teledart/src/teledart/fetch/long_polling.dart:117:7)
...
```
This is a normal error, but I can't catch and handle it in the code,
Because the Future is not passed to the outside,
If an error occurs, the application will exit directly.

```dart teledart.dart
void start() {
    fetcher
      ..start()
      ..onUpdate().listen((_updatesHandler));
  }
```

```dart long_polling.dart
  /// Private long polling loop, throws [LongPollingException] on error.
  /// Automatically retry on exception except HTTP Client error (400).
  /// Double the retry delay timeout on each error, resets timeout on success.
  Future<void> _recursivePolling() {
    if (_isPolling) {
      telegram
          .getUpdates(
              offset: offset,
              limit: limit,
              timeout: timeout,
              allowedUpdates: allowedUpdates)
          .then((updates) {
        if (updates.isNotEmpty) {
          for (var update in updates) {
            emitUpdate(update);
            offset = update.updateId + 1;
          }
        }
        _resetRetryDelay();
        _recursivePolling();
      }).catchError((error) {
        error is HttpClientException
            ? _onRecursivePollingHttpError(error)
            : _onRecursivePollingError(error);
      });
    }
    return Future.value();
  }
```

## To Reproduce
Snippet to reproduce the behavior:
```dart
final teleDart = await Telegram('token')
        .getMe()
        .then((value) => TeleDart('token', Event(value.username!)));

teleDart!.start();
```

## Expected behavior
Pass the Future that throws the error back to the outside

**Comment by The0xArchitect** [comment]
In my opinion, this is already in the right behavior. It's best not to address the 409: Conflict error.

As you already know, the conflict error arises when multiple `getUpdates` calls occur simultaneously. This situation should ideally be prevented, and the behavior should result in termination.

**Comment by DinoLeung** [comment]
@MagicalWater please make sure there's only one instance of `teledart` using the same API key getting updates using the long poll method. if the current `long_polling` update fetcher does not suit your use case, you could write your own implementation be implementing the `AbstractUpdateFetcher`
