### ISSUE TITLE
400 Bad Request: field "keyboard" of the ReplyKeyboardMarkup should be an Array of Arrays

### ISSUE THREAD

**Issue by YevhenKap** [DinoLeung/TeleDart#34]
Unhandled exception:
HttpClientException: HttpClientException: 400 Bad Request: field "keyboard" of the ReplyKeyboardMarkup should be an Array of Arrays
#0      Telegram.sendMessage (package:teledart/src/telegram/telegram.dart:109:29)
<asynchronous suspension>
...

**Comment by DinoLeung** [comment]
Thanks for pointing this out, a hot fix will be up in a few minutes
