### ISSUE TITLE
Handling regular user's message.

### ISSUE THREAD

**Issue by YevhenKap** [DinoLeung/TeleDart#40]
Method `onMessage(...)` - handles all messages (commands, regular messages and so on).
When I try write `/start` in chat:
```dart
await _t.startFetching();
_t.onCommand('start').listen((msg) => _t.replyMessage(msg, 'text'));
_t.onMessage().listen((msg) => _t.replyMessage(msg, 'next text'));
```
All this methods are catch the same `msg` object and both of them print their message. I think it is unacceptable behavior. `onMessage(...)` don't need be able catch everything, why then more precise methods are created? Maybe I wrote a bad code?

**Comment by DinoLeung** [comment]
@YevhenKap thanks for raising another issue.

The code you wrote is valid, and I can see where you were coming from. If you have a look at the implementation of [teledart.onCommand()](https://github.com/DinoLeung/TeleDart/blob/5827652d8e41b6c153a526a51969f7b90e2bcbc9/lib/src/teledart/teledart.dart#L189) and other listeners, you will see they are actually `teledart.onMessage()` under the hood. The idea behind it is to provide short hands, allow you to write cleaner code while offering some degree of flexibility.

For example, if I'm writing a bot to log how active members are in a group, I would like to count every messages in the group. At the same time, the bot still need to response to a few bot commands. `teledart.onMessage()` comes handy in this case logging every messages, then I can use `teledart.onCommand()` to catch commands. 

I hope it all make sense to you, and answered your question.

**Comment by YevhenKap** [comment]
@DinoLeung I agree with you. But I mean that maybe there must be yet one method for handling user's regular messages like `onRegularMessage` etc. Because currently we must write some filters in order to not catch ALL useless events of `onMessage` method for listening only regular messages.

**Comment by DinoLeung** [comment]
@YevhenKap can you elaborate with an example. 
I am guessing you are looking for a `onMessage` to listen to certain keywords. Currently you could do the follow: 

```
_t.onMessage(keyword: 'dart').listen((msg) => _t.replyMessage(msg, 'next text'));  
```

And `keyword` accepts regular expressions. Hope this is what you looking for.

**Comment by YevhenKap** [comment]
I have the following code. Without method `where()` of `onMessage` it catches all messages and command `/start`. I don't need provide `keyword`, because I don't know which words and sentences my bot will catch in future. So I thought it would be useful to create a method that catch all messages except commands, inline queries or something else that have special meanings.
```dart
_t.onCommand('start').listen((msg) {
      keyboard = <List<KeyboardButton>>[<KeyboardButton>[
          KeyboardButton(text: 'Нет'),
          KeyboardButton(text: 'Да')
        ]];
      markup = ReplyKeyboardMarkup(keyboard: keyboard, one_time_keyboard: true, resize_keyboard: true);
      _t.replyMessage(msg, question, reply_markup: markup).whenComplete(() => keyIndex++);
    });
 _t.onMessage()
      .where((msg) => !msg.text.startsWith('/') || msg.text == '')
      .listen(message);
```

**Comment by DinoLeung** [comment]
@YevhenKap Good point. That makes perfect sense, I reckon I would make the following changes in the next update to archive this.

Make `onMessage()` or `onMessage(entityType: null)` to catch regular messages with no `entityType`; `onMessage(entityType: '*')` to catch messages with all `entityType`. 

As a short term solution, my I suggest you the following work around?
```dart
 _t.onMessage()
      .where((msg) => msg.entities == null || msg.entities.length == 0)
      .listen(message);
```

**Comment by YevhenKap** [comment]
@DinoLeung Oh, yes, I agree with you about change `onMessage` method. 

And thank for your suggest about work around! It helps me)
