### ISSUE TITLE
The example is not running

### ISSUE THREAD

**Issue by luisclaudiogama** [DinoLeung/TeleDart#59]
I put my Token Telegram to test this example...(I´m sure my Token is Ok, because it´s running under my Qt application and my site ).

The "start" method is not  working.

I updated all my dependecies like this example.

This is the message error:

Unhandled exception:
TeleDartException: TeleDartException: HttpClientException: HttpClientException: 404 Not Found
#0      TeleDart.start.<anonymous closure> (package:teledart/src/teledart/teledart.dart:70:27)
#1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleError (dart:async/future_impl.dart:144:20)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#5      Future._completeError (dart:async/future_impl.dart:491:5)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#7      _Completer.completeError (dart:async/future_impl.dart:27:5)
#8      _RootZone.runBinary (dart:async/zone.dart:1384:54)
#9      _FutureListener.handleError (dart:async/future_impl.dart:140:20)
#10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#11     Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#12     Future._completeError (dart:async/future_impl.dart:491:5)
#13     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#14     _Completer.completeError (dart:async/future_impl.dart:27:5)
#15     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:18)
#16     Telegram.getMe (package:teledart/src/telegram/telegram.dart)
<asynchronous suspension>
#17     TeleDart._initBotInfo (package:teledart/src/teledart/teledart.dart:39:49)
<asynchronous suspension>
#18     TeleDart.start (package:teledart/src/teledart/teledart.dart:53:13)
<asynchronous suspension>
#19     main (file:///mnt/midia4/prj/Android/Telegram/bin/main.dart:14:12)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

Am I doing anything wrong?
Greetings

**Comment by DinoLeung** [comment]
@luisclaudiogama From the error message, it looks to me that Telegram server cannot find a bot with your token, so it returns a `404` error. Could you request a new token from bot father then try again? 
In case you are not aware of, the example is assuming you store your bot token as an environment variable named `BOT_TOKEN`. If you are running the application in bash, you will need to have something like the following line in your `.bash_profile` file
```
export BOT_TOKEN="123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
```

**Comment by luisclaudiogama** [comment]
@DinoLeung you are correct....I didn´t study your code correctly.

 I changed the inicialization to 
  TeleDart teledart = TeleDart(Telegram([  [my token here] ), Event());
And the message has been sent!!!

I´m sorry for my mistake!

Thank you for the prompt response and congratulations for your excelent job!

greetings from Brazil

**Comment by DinoLeung** [comment]
No worries, glad I can help. I will go ahead and close this issue.
