### ISSUE TITLE
Using Filters

### ISSUE THREAD

**Issue by dev8tg** [DinoLeung/TeleDart#62]
So far we’ve seen how to register a callback function that executes every time a specific update comes from the server, but there’s much more than that to come.

Here we’ll discuss about `Filters.` Filters enable a fine-grain control over what kind of updates are allowed or not to be passed in your callback functions, based on their inner details.

Like What Pyrogram Do [Here](https://docs.pyrogram.org/topics/filters)

More details [Here](https://docs.pyrogram.org/api/filters?highlight=command)

**Comment by DinoLeung** [comment]
@dev8tg this can be done when you define your webhook or long poll, you can assign `allowed_updates` when you initialise them.
see https://pub.dev/documentation/teledart/latest/teledart/TeleDart/setupLongPolling.html and https://pub.dev/documentation/teledart/latest/teledart/TeleDart/setupWebhook.html
see also https://core.telegram.org/bots/api#getupdates and https://core.telegram.org/bots/api#setwebhook
