### ISSUE TITLE
edit on .onCommand

### ISSUE THREAD

**Issue by dev8tg** [DinoLeung/TeleDart#64]
Make *.onCommand* accept list of commands
like `.onCommand(["start", "help"])` and when user send */start* or */help* will get same message

Also *prefix* with on commands to select what command use
Like `.onCommand("start", prefix: ["!", "/", "#"])`
That is mean if message */start* or */start* or *#start* will deal with it as command and reply

**Comment by DinoLeung** [comment]
@YevhenKap do you have an opinion with the list command suggestion (`.onCommand(["start", "help"])`) ? Do you think we need this?

@dev8tg with the command prefix thing, I think it is unlikely I will add to the library. Reason being this library is developed to support telegram defined message pattern, only commands start with `/` will be defined as `bot_command ` see https://core.telegram.org/bots/api#messageentity . Currently, you can achieve the same with `onMessage()` by omitting `entityType` and pass a regular expression string to `keyword`

**Comment by YevhenKap** [comment]
@DinoLeung I think it isn't necessary to add list command parameter to `onCommand(...)`. To determine what method must be called, we will need iterate over the array of commands (in any case accomplish search algorithm on data if parameter will not be an array, but Set or SplayTreeSet, or something else). That operation in a small application isn't meaningful in time, but in large bot application it will slow speed of the bot and slow down the response. 
As an addition, it will take more place in the heap memory region, so...

**Comment by DinoLeung** [comment]
Thanks @YevhenKap I was thinking about the performance hit too , and from the implementation perspective it will complicate stuff up also (the current events handler is pretty messy not to mention, I need to clean that up also).  
I'll go ahead and close this issue. Thanks.

**Comment by DinoLeung** [comment]
@dev8tg with the list command parameter matter, I would suggest the following pattern, although it is not as clean as `.onCommand(['start', 'help'])`.

```
void sendCoolMessage(Message msg) => teledart.replyMessage(msg, 'Hello!');

teledart.onCommand('start').listen(sendCoolMessage);
teledart.onCommand('help').listen(sendCoolMessage);
```
