### ISSUE TITLE
Forward as copy

### ISSUE THREAD

**Issue by dev8tg** [DinoLeung/TeleDart#66]
Telegram have method to forward message but when you forward it will show you *"forward from x user or x channel"*

Add parameter with forward function 
`as_copy (bool, optional)` – Pass True to forward messages without the forward header (i.e.: send a copy of the message content).

That will send same message like a normal message not forwarded

**Comment by DinoLeung** [comment]
@dev8tg this is something on my list to implement 👍

**Comment by eherediadev** [comment]
Any updates?

**Comment by DinoLeung** [comment]
@eherediadev it's supported by the latest [https://core.telegram.org/bots/api#november-4-2020](Bot API 5.0) see the implementation below
https://github.com/DinoLeung/TeleDart/blob/9302e6cf10110d71d1c88130d304760ff0cafeb9/lib/src/telegram/telegram.dart#L226
