### ISSUE TITLE
Can't send Polls

### ISSUE THREAD

**Issue by banalg** [DinoLeung/TeleDart#70]
## Describe the bug
When trying to send a poll a get :
```dart
Unhandled exception:
HttpClientException: HttpClientException: 400 Bad Request: can't parse options JSON object
#0      Telegram.sendPoll (package:teledart/src/telegram/telegram.dart:830:29)
```

## To Reproduce
Snippet to reproduce the behavior:
```dart
sendPoll(22, "My Question", List<String>()..addAll(['Choice1', 'Choice2']));
```

## To solve
Replace in method **Telegram.sendPoll** (line 824)
https://github.com/DinoLeung/TeleDart/blob/master/lib/src/telegram/telegram.dart#L825
```dart
'options': options,
```
by
```dart
'options': jsonEncode(options),
```

**Comment by DinoLeung** [comment]
@banalg thanks for raising issues, a hot fix will be up later 👍
