### ISSUE TITLE
Flutter app usage advice

### ISSUE THREAD

**Issue by winwisely99** [DinoLeung/TeleDart#83]
Is there anything preventing this being used as a communications system from inside a Flutter app.
Sorry i am so lazy about checking the transport but ...

I assume that https://github.com/DinoLeung/DartWiseBot could just also be wrapped with a Dart GRPC, and then the Flutter GRPC uses it.

But i was hoping to be able to go direct from Flutter to Telegram without a Server in the middle.

The other way is to embed golang inside the FLutter app using https://github.com/go-telegram-bot-api/telegram-bot-api
thats just a gomobile compile away and some tinkering.

**Comment by DinoLeung** [comment]
Thanks for reaching @winwisely99 
I reckon you could use Teledart dirrectly in your Flutter application with no problems, it uses the official [http client](https://pub.dev/packages/http) to interact with the telegram bots api. As long as you can require the http library in your flutter app, I don't see any issue would stop you from requiring Teledart and host a bot from a mobile device. 😎

**Comment by winwisely99** [comment]
Ok makes perfect sense. It's just long polling 

Thank you !!
