### ISSUE TITLE
Change primitives to Dart correspondents

### ISSUE THREAD

**Issue by shinayser** [DinoLeung/TeleDart#84]
Hello! Such an amazing library! Thank you so much for your work.

I am using it on a side project but I realized that some properties are impossible to know it's meaning by just looking into the code. For example:

- The `Message` class has a propery named `date` (and `forward_date` and `edit_date`), as an `int` value. But what doest it mean? Is it milliseconds since epoch or microseconds? And it is UTC date?
-  The class `Audio` has a `int` property named `duration`. Is it seconds, milliseconds or microseconds?

For those two problems above there are 2 simple solutions:

1. Change dates to `DateTime` objects.
2. Change duration property to `Duration` objects.

Both are dart native objects :)
Hope you consider that request.

Best regards!

**Comment by DinoLeung** [comment]
Good idea @shinayser 

As far as I know, the date integers are unix timestamps, and `duration` in `Audio` object (and other media objects) are in seconds. (see bots api docs)

**Comment by shinayser** [comment]
I understand when you say that `objects defined in the telegram lib should appear the same as the official telegram bot api documentation` but before this library being a telegram library, it is a Dart library.

Using the dart-lang objects would make the library much easier to use, for dart developers (of course 😆). A lot of those dart objects are wrappers to simplify our life, like the `Duration` one.

And if you think that there is no documentation on the current version, those objects could be very hand on helping developers finding out what they mean.

Hope this clarify. If you need any help on this implementation just let me know 😊
