### ISSUE TITLE
Using proxy

### ISSUE THREAD

**Issue by benone** [DinoLeung/TeleDart#85]
It would be great to support proxies for countries like Russia where telegram is blocked :)

**Comment by DinoLeung** [comment]
Hi @benone 
I think it would make more sense to setup proxy connection on the host machine itself, that way both incoming and outgoing requests are going through the proxy server. 
See `Turning proxies on and off`:
https://api.dart.dev/stable/1.10.1/dart-io/HttpClient-class.html
