### ISSUE TITLE
About node.js support

### ISSUE THREAD

**Issue by shinayser** [DinoLeung/TeleDart#86]
Hello Dino!

I just forked your repository and was trying to make a compatilble version of the library with the javascript generated by https://pub.dev/packages/build_node_compilers

It is actually easy to make a node compatible project. I just added some conditional imports to teledart to import either the standard `dart:io` and `http` or the `node_io` or  `node_http` depending on the build environment.

This is the current import for your `http_client` class:

![image](https://user-images.githubusercontent.com/1146982/73665966-ca2e1f80-4680-11ea-80c8-1b6bec60aa67.png)

But there is a huge issue. Not all methods and classes from `http` are implemented on `node_http`, and one of the is the `MultipartRequest` . Also, the `SecurityContext` the you use on the class `WebHook` also is not implemented yet.

This are some erros we get when trying to compile it to node:

```dart
Error: 'MultipartFile' isn't a type.
  Future<dynamic> httpMultipartPost(String url, List<http.MultipartFile> files,
                                                          ^^^^^^^^^^^^^
Error: Method not found: 'MultipartRequest'.
    var request = http.MultipartRequest('POST', Uri.parse(url))
                  ^^^^^^^^^^^^^^^^
Error: Method not found: 'HttpServer.bindSecure'.
    Future<dynamic> serverFuture = io.HttpServer.bindSecure(
                                                 ^^^^^^^^^^
-------------------------------------------------------------------------------
Error: Method not found: 'SecurityContext'.
    _context = io.SecurityContext();
               ^^^^^^^^^^^^^^^
Error: Getter not found: 'anyIPv4'.
        io.InternetAddress.anyIPv4.address, port, _context);
                           ^^^^^^^
```

My question is: are those classes really needed for the working of the library? There is a way to replace them by other types?

What do you think?

**Comment by DinoLeung** [comment]
Hi @shinayser those classes are certainly required enable the library to communicate with telegram server. e.g. `MultipartFile` and `MultipartRequest` are utilised to make post requests with files; `bindSecure`, `SecurityContext` and `anyIPv4` are required to setup webhook if user chose to. 
Although, you could drop the support of webhook and file upload in order to provide basic functionality.
