### ISSUE TITLE
There is no way to disable case sensitivity in the onMessage method

### ISSUE THREAD

**Issue by jarcoder** [DinoLeung/TeleDart#92]
Hello!
Thank you for your work! We need to do something similar to the NLP algorithm. But, we cannot change the case sensitivity with the help of additional parameters. And we cannot change the case sensitivity in the RegExp object with the necessary parameters. 
So you have to write something like this:
teledart.onMessage (keyword: r '(Hi|hi|hI|HI)')

**Comment by DinoLeung** [comment]
Hi @jarcoder 

see the example below, you can set `caseSensitive` to `false`, and it will match the word `hello` in any case combination.

```
RegExp exp = new RegExp(r"hello", caseSensitive: false);
```

**Comment by DinoLeung** [comment]
@jarcoder my bad, currently `onMessage` accepts only `string`. I will make it accept `RegExp` objects
