### ISSUE TITLE
how to delete message?

### ISSUE THREAD

**Issue by paulobreim** [DinoLeung/TeleDart#94]
Can you give me a example how to delete a message?

There are no method when I try use  teledart.deleteMessage(chat_id, message_id);

 Thank you

**Comment by paulobreim** [comment]
I found

**Comment by DinoLeung** [comment]
@paulobreim see: https://github.com/DinoLeung/TeleDart/blob/dc79f69830dd5c528e440f5e60a99c4a54ca83dd/lib/src/telegram/telegram.dart#L1472
